### ISSUE TITLE
Use underscore for custom extension prefix

### ISSUE THREAD

**Issue by gadomski** [pjhartzell/usgs-lcmap#1]
I don't know if there's a document to reference, but we've been using `_` characters for extension prefixes, e.g. https://github.com/stac-extensions/usfws-nwi/. `usgs-lcmap:` should be changed to `usgs_lcmap:`.

**Comment by pjhartzell** [comment]
Ah. Good to know. Fixed in [c8504fea993946fcac9cbf8e6465b3785bed7318 ](https://github.com/stactools-packages/usgs-lcmap/commit/c8504fea993946fcac9cbf8e6465b3785bed7318)
